[tools]
node = "24.21.0"
java = "25.0.2"
elixir = "1.20.4-otp-29"
erlang = "29.0.6"
lua-language-server = "latest"
elixir-ls = "latest"
tree-sitter = "latest"
"npm:typescript" = "7.0.2"
biome = "latest"
"github:artempyanykh/marksman" = "latest"
