[tools]
node = "24.18.0"
java = "25.0.2"
lua-language-server = "latest"
elixir-ls = "latest"
erlang = "29.0.2"
elixir = "1.20.2-otp-29"
tree-sitter = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"github:artempyanykh/marksman" = "latest"
