set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
set -g pane-base-index 1

set-option -g prefix C-Space
set-option -g prefix2 none

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind w switch-client -T w-table
bind-key -T w-table v split-window -h -c "#{pane_current_path}"
bind-key -T w-table s split-window -v -c "#{pane_current_path}"
bind-key -T w-table h select-pane -L
bind-key -T w-table j select-pane -D
bind-key -T w-table k select-pane -U
bind-key -T w-table l select-pane -R

bind Space copy-mode

# resizing panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# mouse support
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind x kill-pane
bind n new-window
bind [ previous-window
bind ] next-window

# Pane borders
set -g pane-border-style "fg=#2a2a2a"
set -g pane-active-border-style "fg=#555555"

# Status bar
set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=default,fg=#b8b8b8"

set -g status-left ""

set -g status-right-length 80
set -g status-right "#{?client_prefix,#[fg=#d8d8d8],#[fg=#555555]} 󰌌 #[fg=#b8b8b8] #(printf '') #{b:pane_current_path}  #(cd #{pane_current_path} && git branch --show-current 2>/dev/null | xargs -I{} printf ' {}')  #(printf '') #S "

setw -g window-status-format "#[fg=#555555] #I:#W#{?window_zoomed_flag, Z,} "
setw -g window-status-current-format "#[fg=#d8d8d8,bold] #I:#W#{?window_zoomed_flag, Z,} "
setw -g window-status-separator ""
