set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
set -g pane-base-index 1

set-option -g prefix C-Space
set-option -g prefix2 none

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind w switch-client -T w-table
bind-key -T w-table v split-window -h -c "#{pane_current_path}"
bind-key -T w-table s split-window -v -c "#{pane_current_path}"

bind Space copy-mode

# resizing panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# mouse support
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key -r f run-shell "tmux neww ~/scripts/tmux-sessionnizer"
bind-key n command-prompt "new-session -s '%%'"
