general {
    hide_cursor        = true
    grace              = 0
    ignore_empty_input = true
    no_fade_in         = false
}

background {
    monitor =
    color   = rgba(000000ff)
}

input-field {
    monitor          =
    size             = 250, 50
    outline_thickness = 1
    dots_size        = 0.25
    dots_spacing     = 0.3
    dots_center      = true
    outer_color      = rgba(333333ff)
    inner_color      = rgba(0d0d0dff)
    font_color       = rgba(ffffffff)
    fade_on_empty    = false
    placeholder_text = <span foreground="##999999">Password...</span>
    fail_color       = rgba(ccccccff)
    fail_text        = <span foreground="##cccccc">$FAIL <b>($ATTEMPTS)</b></span>
    position         = 0, -100
    halign           = center
    valign           = center
}

label {
    monitor     =
    text        = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size   = 90
    font_family = JetBrainsMono Nerd Font
    color       = rgba(ffffffff)
    position    = 0, 100
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    font_size   = 18
    font_family = JetBrainsMono Nerd Font
    color       = rgba(999999ff)
    position    = 0, 20
    halign      = center
    valign      = center
}
