# Input configuration
# See https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = br
    kb_variant = abnt2
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0  # -1.0 to 1.0, 0 = no modification

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures/
gesture = 3, horizontal, workspace

# Example config for a specific device
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }
