#!/usr/bin/env bash
#
# setup-cloudflare-dns.sh
#
# Forces ALL system DNS through Cloudflare, encrypted (DNS-over-TLS / DoT),
# IPv4 + IPv6, using the native systemd-resolved stack.
#
# - Sets Cloudflare as the global DNS with strict DoT (no plaintext fallback).
# - Stops systemd-networkd from accepting the ISP's DHCP-provided DNS.
# - Idempotent: safe to run repeatedly / on every fresh install.
#
# Usage:  sudo ./setup-cloudflare-dns.sh
#
set -euo pipefail

# --- require root ------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "This script needs root. Run: sudo $0" >&2
    exit 1
fi

# --- Cloudflare DoT ----------------------------------------------------------
# 1.1.1.1 / 1.0.0.1 (IPv4) and 2606:4700:4700::1111 / ::1001 (IPv6).
# The "#cloudflare-dns.com" enables TLS certificate verification (SNI).
CF_DNS="1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com"

# =============================================================================
# 1. Global resolved DNS, with DoT
# =============================================================================
RESOLVED_DIR="/etc/systemd/resolved.conf.d"
RESOLVED_DROPIN="${RESOLVED_DIR}/cloudflare-dot.conf"

install -d -m 0755 "$RESOLVED_DIR"
cat > "$RESOLVED_DROPIN" <<EOF
# Generated by setup-cloudflare-dns.sh — encrypted Cloudflare DNS (DoT).
[Resolve]
DNS=${CF_DNS}
# No fallback: never drop to a non-Cloudflare plaintext resolver.
FallbackDNS=
# Strict DoT: if it can't be encrypted, the query fails (no leaking).
DNSOverTLS=yes
# Validate DNSSEC when the server supports it (Cloudflare does).
DNSSEC=allow-downgrade
# Route ALL lookups to the global DNS (ignore per-link search domains).
Domains=~.
EOF
echo "==> resolved: wrote $RESOLVED_DROPIN"

# =============================================================================
# 2. Stop systemd-networkd from using DHCP-provided DNS
#    (otherwise the ISP DNS stays active per-link and wins over the global one)
# =============================================================================
NET_DIR="/etc/systemd/network"
shopt -s nullglob
networks=("$NET_DIR"/*.network)

if [[ ${#networks[@]} -eq 0 ]]; then
    echo "==> Warning: no *.network files in $NET_DIR (no per-link DNS, fine)."
else
    for net in "${networks[@]}"; do
        dropdir="${net}.d"
        install -d -m 0755 "$dropdir"
        cat > "${dropdir}/10-no-dhcp-dns.conf" <<'EOF'
# Generated by setup-cloudflare-dns.sh — ignore DHCP/RA-provided DNS.
[DHCPv4]
UseDNS=no
[DHCPv6]
UseDNS=no
[IPv6AcceptRA]
UseDNS=no
EOF
        echo "==> networkd: wrote ${dropdir}/10-no-dhcp-dns.conf"
    done
fi

# =============================================================================
# 3. Ensure /etc/resolv.conf points at the resolved stub
# =============================================================================
STUB="/run/systemd/resolve/stub-resolv.conf"
if [[ "$(readlink -f /etc/resolv.conf 2>/dev/null || true)" != "$STUB" ]]; then
    ln -sf "$STUB" /etc/resolv.conf
    echo "==> /etc/resolv.conf -> $STUB"
else
    echo "==> /etc/resolv.conf already points at the resolved stub"
fi

# =============================================================================
# 4. Enable / restart services
# =============================================================================
systemctl enable --now systemd-resolved
systemctl restart systemd-resolved
# only restart networkd if it is actually in use
if systemctl is-active --quiet systemd-networkd; then
    systemctl restart systemd-networkd
fi

# give the link a moment to come back up before verifying
sleep 2

# =============================================================================
# 5. Verification
# =============================================================================
echo
echo "=================== VERIFICATION ==================="
resolvectl status | grep -E "Current DNS|DNS Servers|DNSOverTLS|DNSSEC|Protocols" || true
echo "---------------------------------------------------"
echo "Resolution test (should show +DNSOverTLS above):"
resolvectl query cloudflare.com || true
echo "==================================================="
echo
echo "Done. Tip: confirm at https://1.1.1.1/help  ->  'Using DNS over TLS (DoT)' = Yes"
