vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end

vim.o.termguicolors = true
vim.o.background = 'dark'
vim.g.colors_name = 'mono'

local p = {
  bg      = '#000000',
  bg_alt  = '#0d0d0d',
  bg_ui   = '#161616',
  bg_sel  = '#262626',
  bg_hi   = '#333333',

  fg      = '#b3b3b3',
  fg_dim  = '#808080',
  fg_mute = '#4d4d4d',
  fg_hi   = '#ffffff',

  border  = '#333333',

  grey_dk = '#333333',
  grey    = '#999999',
  grey_lt = '#cccccc',
  white   = '#ffffff',
  black   = '#0d0d0d',

  -- muted hues — colorful enough to tell syntax apart at a glance, still grounded in grey
  clay    = '#a47d72',
  sage    = '#889781',
  sand    = '#a79a7d',
  slate   = '#78899d',
  mauve   = '#988599',
  teal    = '#7f9b97',

  clay_b  = '#c29c8f',
  sage_b  = '#a5b79d',
  sand_b  = '#c6ba9a',
  slate_b = '#96a8bd',
  mauve_b = '#b7a4b8',
  teal_b  = '#9eb9b4',
}

local role = {
  keyword  = p.mauve_b,
  string   = p.sage,
  func     = p.slate_b,
  type     = p.sand_b,
  const    = p.teal_b,
  variable = p.fg,
  comment  = p.fg_mute,
  error    = p.clay_b,
  warn     = p.sand_b,
  info     = p.slate_b,
  hint     = p.teal_b,
  added    = p.sage,
  changed  = p.slate,
  removed  = p.clay,
}

local groups = {
  Normal       = { fg = p.fg, bg = 'NONE' },
  NormalNC     = { fg = p.fg, bg = 'NONE' },
  NormalFloat  = { fg = p.fg, bg = p.bg_ui },
  FloatBorder  = { fg = p.border, bg = p.bg_ui },
  FloatTitle   = { fg = p.fg_hi, bg = p.bg_ui, bold = true },

  Cursor       = { fg = p.bg, bg = p.fg_hi },
  lCursor      = { fg = p.bg, bg = p.fg_hi },
  CursorLine   = { bg = p.bg_alt },
  CursorColumn = { bg = p.bg_alt },
  ColorColumn  = { bg = p.bg_alt },

  LineNr       = { fg = p.fg_mute },
  CursorLineNr = { fg = p.fg_hi, bold = true },
  SignColumn   = { bg = 'NONE' },
  FoldColumn   = { fg = p.fg_mute, bg = 'NONE' },
  Folded       = { fg = p.fg_dim, bg = p.bg_alt },

  Visual       = { bg = p.bg_sel },
  VisualNOS    = { bg = p.bg_sel },
  Search       = { fg = p.bg, bg = p.fg_hi },
  IncSearch    = { fg = p.bg, bg = p.fg_hi, bold = true },
  CurSearch    = { fg = p.bg, bg = p.fg_hi, bold = true },
  MatchParen   = { fg = p.fg_hi, bold = true, underline = true },

  WinSeparator = { fg = p.border },
  VertSplit    = { fg = p.border },

  Pmenu        = { fg = p.fg, bg = p.bg_ui },
  PmenuSel     = { fg = p.bg, bg = p.fg_hi, bold = true },
  PmenuSbar    = { bg = p.bg_ui },
  PmenuThumb   = { bg = p.grey },
  PmenuKind    = { fg = role.type, bg = p.bg_ui },
  PmenuExtra   = { fg = p.fg_mute, bg = p.bg_ui },
  WildMenu     = { link = 'PmenuSel' },

  StatusLine   = { fg = p.fg_dim, bg = 'NONE', sp = p.border, overline = true },
  StatusLineNC = { fg = p.fg_mute, bg = 'NONE', sp = p.border, overline = true },
  TabLine      = { fg = p.fg_mute, bg = p.bg_alt },
  TabLineFill  = { bg = 'NONE' },
  TabLineSel   = { fg = p.bg, bg = p.fg_hi, bold = true },
  WinBar       = { fg = p.fg_dim, bg = 'NONE' },
  WinBarNC     = { fg = p.fg_mute, bg = 'NONE' },

  Directory    = { fg = role.func },
  Title        = { fg = p.fg_hi, bold = true },
  Question     = { fg = role.info },
  MoreMsg      = { fg = role.added },
  ModeMsg      = { fg = p.fg_dim },
  ErrorMsg     = { fg = role.error, bold = true },
  WarningMsg   = { fg = role.warn },
  NonText      = { fg = p.grey_dk },
  Whitespace   = { fg = p.grey_dk },
  SpecialKey   = { fg = p.grey_dk },
  Conceal      = { fg = p.fg_dim },
  EndOfBuffer  = { fg = p.bg },
  QuickFixLine = { bg = p.bg_sel },

  SpellBad     = { sp = role.error, undercurl = true },
  SpellCap     = { sp = role.warn, undercurl = true },
  SpellRare    = { sp = role.hint, undercurl = true },
  SpellLocal   = { sp = role.info, undercurl = true },

  Comment        = { fg = role.comment, italic = true },
  Constant       = { fg = role.const },
  String         = { fg = role.string, italic = true },
  Character      = { fg = role.string, italic = true },
  Number         = { fg = role.const },
  Boolean        = { fg = role.const },
  Float          = { fg = role.const },

  Identifier     = { fg = role.variable },
  Function       = { fg = role.func, bold = true },

  Statement      = { fg = role.keyword, bold = true },
  Conditional    = { fg = role.keyword, bold = true },
  Repeat         = { fg = role.keyword, bold = true },
  Label          = { fg = role.keyword, bold = true },
  Operator       = { fg = p.fg_dim },
  Keyword        = { fg = role.keyword, bold = true },
  Exception      = { fg = role.keyword, bold = true },

  PreProc        = { fg = p.mauve, italic = true },
  Include        = { fg = role.keyword, bold = true },
  Define         = { fg = role.keyword, bold = true },
  Macro          = { fg = p.mauve, italic = true },
  PreCondit      = { fg = role.keyword, bold = true },

  Type           = { fg = role.type },
  StorageClass   = { fg = role.keyword, bold = true },
  Structure      = { fg = role.type },
  Typedef        = { fg = role.type },

  Special        = { fg = p.teal },
  SpecialChar    = { fg = p.teal_b },
  Delimiter      = { fg = p.fg_dim },
  Tag            = { fg = role.type },
  Debug          = { fg = role.error },

  Underlined     = { underline = true },
  Ignore         = { fg = p.fg_mute },
  Error          = { fg = role.error, bold = true },
  Todo           = { fg = p.bg, bg = p.fg_hi, bold = true },

  ['@variable']              = { fg = role.variable },
  ['@variable.builtin']      = { fg = p.mauve, italic = true },
  ['@variable.parameter']    = { fg = p.fg, italic = true },
  ['@variable.member']       = { fg = p.grey },

  ['@constant']              = { fg = role.const },
  ['@constant.builtin']      = { fg = role.const, italic = true },
  ['@constant.macro']        = { fg = p.mauve },

  ['@module']                = { fg = role.type },
  ['@label']                 = { fg = role.keyword, bold = true },

  ['@string']                = { fg = role.string, italic = true },
  ['@string.escape']         = { fg = p.teal_b, bold = true },
  ['@string.special']        = { fg = p.teal_b },
  ['@string.regexp']         = { fg = p.sage },
  ['@character']             = { fg = role.string, italic = true },

  ['@boolean']               = { fg = role.const },
  ['@number']                = { fg = role.const },

  ['@function']              = { fg = role.func, bold = true },
  ['@function.builtin']      = { fg = role.func, italic = true },
  ['@function.call']         = { fg = role.func },
  ['@function.macro']        = { fg = p.mauve },
  ['@function.method']       = { fg = role.func },
  ['@function.method.call']  = { fg = role.func },
  ['@constructor']           = { fg = role.type },

  ['@operator']              = { fg = p.fg_dim },
  ['@keyword']               = { fg = role.keyword, bold = true },
  ['@keyword.function']      = { fg = role.keyword, bold = true },
  ['@keyword.operator']      = { fg = role.keyword },
  ['@keyword.return']        = { fg = p.mauve_b, bold = true, underline = true },
  ['@keyword.conditional']   = { fg = role.keyword, bold = true },
  ['@keyword.repeat']        = { fg = role.keyword, bold = true },
  ['@keyword.import']        = { fg = role.keyword, bold = true },
  ['@keyword.exception']     = { fg = role.keyword, bold = true },

  ['@punctuation.delimiter'] = { fg = p.fg_dim },
  ['@punctuation.bracket']   = { fg = p.fg_dim },
  ['@punctuation.special']   = { fg = p.teal },

  ['@type']                  = { fg = role.type },
  ['@type.builtin']          = { fg = role.type, italic = true },
  ['@type.definition']       = { fg = role.type },
  ['@attribute']             = { fg = p.mauve, italic = true },
  ['@property']              = { fg = p.grey },

  ['@comment']               = { fg = role.comment, italic = true },
  ['@comment.error']         = { fg = p.bg, bg = role.error, bold = true },
  ['@comment.warning']       = { fg = p.bg, bg = role.warn, bold = true },
  ['@comment.todo']          = { fg = p.bg, bg = p.fg_hi, bold = true },
  ['@comment.note']          = { fg = p.bg, bg = role.hint, bold = true },

  ['@tag']                   = { fg = role.keyword },
  ['@tag.builtin']           = { fg = role.keyword },
  ['@tag.attribute']         = { fg = role.func },
  ['@tag.delimiter']         = { fg = p.fg_dim },

  ['@markup.strong']         = { fg = p.fg_hi, bold = true },
  ['@markup.italic']         = { italic = true },
  ['@markup.strikethrough']  = { strikethrough = true },
  ['@markup.underline']      = { underline = true },
  ['@markup.heading']        = { fg = p.sage_b, bold = true },
  ['@markup.heading.1']      = { fg = p.sage_b, bold = true },
  ['@markup.heading.2']      = { fg = p.teal_b, bold = true },
  ['@markup.heading.3']      = { fg = p.slate_b, bold = true },
  ['@markup.heading.4']      = { fg = p.mauve_b, bold = true },
  ['@markup.heading.5']      = { fg = p.sand_b, bold = true },
  ['@markup.heading.6']      = { fg = p.grey, bold = true },
  ['@markup.quote']          = { fg = p.fg_dim, italic = true },
  ['@markup.link']           = { fg = role.func, underline = true },
  ['@markup.link.label']     = { fg = role.const },
  ['@markup.link.url']       = { fg = p.fg_mute, underline = true },
  ['@markup.raw']            = { fg = role.string },
  ['@markup.list']           = { fg = p.teal },
  ['@markup.list.checked']   = { fg = role.added },
  ['@markup.list.unchecked'] = { fg = p.fg_dim },

  ['@diff.plus']             = { fg = role.added },
  ['@diff.minus']            = { fg = role.removed, strikethrough = true },
  ['@diff.delta']            = { fg = role.changed },

  ['@lsp.type.class']         = { link = '@type' },
  ['@lsp.type.enum']          = { link = '@type' },
  ['@lsp.type.enumMember']    = { link = '@constant' },
  ['@lsp.type.interface']     = { link = '@type' },
  ['@lsp.type.function']      = { link = '@function' },
  ['@lsp.type.method']        = { link = '@function.method' },
  ['@lsp.type.namespace']     = { link = '@module' },
  ['@lsp.type.parameter']     = { link = '@variable.parameter' },
  ['@lsp.type.property']      = { link = '@property' },
  ['@lsp.type.struct']        = { link = '@type' },
  ['@lsp.type.type']          = { link = '@type' },
  ['@lsp.type.typeParameter'] = { link = '@type.definition' },
  ['@lsp.type.variable']      = { link = '@variable' },
  ['@lsp.type.decorator']     = { link = '@attribute' },
  ['@lsp.mod.deprecated']     = { strikethrough = true },

  LspReferenceText  = { bg = p.bg_sel },
  LspReferenceRead  = { bg = p.bg_sel },
  LspReferenceWrite = { bg = p.bg_sel, underline = true },
  LspInlayHint      = { fg = p.fg_mute, bg = p.bg_alt, italic = true },
  LspSignatureActiveParameter = { fg = p.fg_hi, bold = true },
  LspCodeLens       = { fg = p.fg_mute, italic = true },

  DiagnosticError = { fg = role.error, bold = true },
  DiagnosticWarn  = { fg = role.warn },
  DiagnosticInfo  = { fg = role.info },
  DiagnosticHint  = { fg = role.hint, italic = true },
  DiagnosticOk    = { fg = role.added },

  DiagnosticVirtualTextError = { fg = role.error, bg = '#1c1414', bold = true },
  DiagnosticVirtualTextWarn  = { fg = role.warn, bg = '#1c1a13' },
  DiagnosticVirtualTextInfo  = { fg = role.info, bg = '#13181c' },
  DiagnosticVirtualTextHint  = { fg = role.hint, bg = '#131c1a', italic = true },

  DiagnosticUnderlineError = { sp = role.error, undercurl = true },
  DiagnosticUnderlineWarn  = { sp = role.warn, undercurl = true },
  DiagnosticUnderlineInfo  = { sp = role.info, undercurl = true },
  DiagnosticUnderlineHint  = { sp = role.hint, undercurl = true },

  DiagnosticUnnecessary = { fg = p.fg_mute },
  DiagnosticDeprecated  = { strikethrough = true },

  DiffAdd    = { bg = '#161c16' },
  DiffChange = { bg = '#151a1e' },
  DiffDelete = { fg = role.removed, bg = '#1e1616' },
  DiffText   = { bg = '#1d2a1d' },
  Added      = { fg = role.added },
  Changed    = { fg = role.changed },
  Removed    = { fg = role.removed, strikethrough = true },

  GitSignsAdd          = { fg = role.added },
  GitSignsChange       = { fg = role.changed },
  GitSignsDelete       = { fg = role.removed },
  GitSignsAddInline    = { bg = '#243024' },
  GitSignsChangeInline = { bg = '#1f2831' },
  GitSignsDeleteInline = { bg = '#302020' },
  GitSignsCurrentLineBlame = { fg = p.fg_mute, italic = true },

  FzfLuaNormal       = { fg = p.fg, bg = p.bg_ui },
  FzfLuaBorder       = { fg = p.border, bg = p.bg_ui },
  FzfLuaTitle        = { fg = p.fg_hi, bg = p.bg_ui, bold = true },
  FzfLuaCursor       = { fg = p.bg, bg = p.fg_hi },
  FzfLuaCursorLine   = { fg = p.fg_hi, bg = p.bg_hi },
  FzfLuaSearch       = { fg = p.fg_hi, bold = true },
  FzfLuaHeaderBind   = { fg = role.func },
  FzfLuaHeaderText   = { fg = p.fg_dim },
  FzfLuaPathColNr    = { fg = p.fg_mute },
  FzfLuaPathLineNr   = { fg = p.fg_mute },
  FzfLuaBufNr        = { fg = role.const },
  FzfLuaBufFlagCur   = { fg = p.fg_hi, bold = true },
  FzfLuaBufFlagAlt   = { fg = role.info },
  FzfLuaLiveSym      = { fg = role.warn },

  OilDir        = { fg = role.func, bold = true },
  OilDirIcon    = { fg = role.func },
  OilLink       = { fg = p.teal_b, underline = true },
  OilLinkTarget = { fg = p.fg_dim },
  OilFile       = { fg = p.fg },
  OilCreate     = { fg = role.added },
  OilDelete     = { fg = role.removed, strikethrough = true },
  OilMove       = { fg = role.changed },
  OilCopy       = { fg = role.hint },
  OilChange     = { fg = role.warn },
  OilRestore    = { fg = role.added },
  OilPurge      = { fg = role.removed },
  OilTrash      = { fg = role.removed },

  WhichKey          = { fg = p.fg_hi, bold = true },
  WhichKeyGroup     = { fg = role.func },
  WhichKeyDesc      = { fg = p.fg },
  WhichKeySeparator = { fg = p.fg_mute },
  WhichKeyFloat     = { bg = p.bg_ui },
  WhichKeyBorder    = { fg = p.border, bg = p.bg_ui },
  WhichKeyTitle     = { fg = p.fg_hi, bg = p.bg_ui, bold = true },
  WhichKeyValue     = { fg = p.fg_mute },

  NeotestPassed       = { fg = role.added },
  NeotestFailed       = { fg = role.error, bold = true },
  NeotestRunning      = { fg = role.warn },
  NeotestSkipped      = { fg = role.info },
  NeotestTest         = { fg = p.fg },
  NeotestNamespace    = { fg = role.type },
  NeotestFile         = { fg = role.func },
  NeotestDir          = { fg = role.func },
  NeotestFocused      = { bold = true, underline = true },
  NeotestAdapterName  = { fg = p.fg_hi, bold = true },
  NeotestIndent       = { fg = p.grey_dk },
  NeotestExpandMarker = { fg = p.grey_dk },
  NeotestMarked       = { fg = p.fg_hi, bold = true },
  NeotestWinSelect    = { fg = role.func, bold = true },

  RenderMarkdownH1Bg       = { fg = p.sage_b,  bg = '#182018', bold = true },
  RenderMarkdownH2Bg       = { fg = p.teal_b,  bg = '#16201f', bold = true },
  RenderMarkdownH3Bg       = { fg = p.slate_b, bg = '#161b20', bold = true },
  RenderMarkdownH4Bg       = { fg = p.mauve_b, bg = '#1c1720', bold = true },
  RenderMarkdownH5Bg       = { fg = p.sand_b,  bg = '#201d16', bold = true },
  RenderMarkdownH6Bg       = { fg = p.grey,    bg = p.bg_alt,  bold = true },
  RenderMarkdownCode       = { bg = p.bg_alt },
  RenderMarkdownCodeInline = { fg = role.string, bg = p.bg_alt },
  RenderMarkdownBullet     = { fg = p.teal },
  RenderMarkdownQuote      = { fg = p.fg_dim },
  RenderMarkdownDash       = { fg = p.border },
  RenderMarkdownLink       = { fg = role.func, underline = true },
  RenderMarkdownChecked    = { fg = role.added },
  RenderMarkdownUnchecked  = { fg = p.fg_dim },
  RenderMarkdownTableHead  = { fg = p.fg_dim },
  RenderMarkdownTableRow   = { fg = p.fg_dim },

  MiniStatuslineModeNormal  = { fg = p.bg, bg = p.sage_b,  bold = true },
  MiniStatuslineModeInsert  = { fg = p.bg, bg = p.slate_b, bold = true },
  MiniStatuslineModeVisual  = { fg = p.bg, bg = p.mauve_b, bold = true },
  MiniStatuslineModeReplace = { fg = p.bg, bg = p.clay_b,  bold = true },
  MiniStatuslineModeCommand = { fg = p.bg, bg = p.sand_b,  bold = true },
  MiniStatuslineModeOther   = { fg = p.bg, bg = p.teal_b,  bold = true },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

local ansi = {
  p.black, p.clay, p.sage, p.sand, p.slate, p.mauve, p.teal, p.grey_lt,
  p.grey_dk, p.clay_b, p.sage_b, p.sand_b, p.slate_b, p.mauve_b, p.teal_b, p.fg_hi,
}
for i, color in ipairs(ansi) do
  vim.g['terminal_color_' .. (i - 1)] = color
end
